language: go
cache: bundler
go:
  - 1.9.x

before_install:
  - go get github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
  - go get github.com/onsi/gomega/...     # fetches the matcher library

script:
  - ginkgo -r -v -cover -coverprofile=coverage.txt -outputdir=. -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
