language: go

go:
  - 1.9.x
  - 1.10.x

before_install:
  - go get -u github.com/onsi/ginkgo/ginkgo  # installs the ginkgo CLI
  - go get -u github.com/onsi/gomega/...     # fetches the matcher library

script:
  - ginkgo -r -v -cover
